"""delete notes table switching to one table

Revision ID: d056498cea39
Revises: cf3a28f2ef90
Create Date: 2020-10-05 14:27:40.396811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd056498cea39'
down_revision = 'cf3a28f2ef90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    op.add_column('verse', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verse', 'notes')
    op.create_table('note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('heading', sa.VARCHAR(length=255), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('verse_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['verse_id'], ['verse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
